#eens4 encoder and tf predictor (15 epochs)
defaults:
  - base: base
  - data@data0: data_shhs_spec
  - encoder: eens4
  - predictor: tf
  - loss: cef
  - encoder_static: none
  - head: rnn
  - quantizer: none
  - trainer: trainer

base:
  lr: 0.001
  batch_size: 16
  fs: 1.
  freq_bins: 129
  metrics: ["f1","macro_auc","accuracy"]
  aggregate_predictions: false
  normalize: false
  input_channels: 5
  input_size: 450
  chunk_length_train: 450
  aggregate_strided_multi_predictions: true
  stride_valtest: 30
  
trainer:
  accumulate: 8
  mainclass: "clinical_ts.cpc_psg.CPCPSG"
  gpus: 1
  refresh_rate: 1
  username: "nstrodt"
  export_predictions: True
  epochs: 30
  precision: 32

loss:
  weight: [ ]

head:
  multi_prediction: true
  local_pool_kernel_size: 1

encoder:
  encoder:
   timesteps_per_token: 1
  epoch_length: 30

predictor:
  model_dim: 256
  causal: false
